// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config">> = Specific
  const handler = {} as typeof import("../../../src/app/api/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dispatch">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guide">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/hermes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hermes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/hermes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models">> = Specific
  const handler = {} as typeof import("../../../src/app/api/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/neurosync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/neurosync">> = Specific
  const handler = {} as typeof import("../../../src/app/api/neurosync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notebook/asset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notebook/asset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notebook/asset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notebook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notebook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notebook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notebooklm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notebooklm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notebooklm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/obsidian/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/obsidian">> = Specific
  const handler = {} as typeof import("../../../src/app/api/obsidian/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/omi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/omi">> = Specific
  const handler = {} as typeof import("../../../src/app/api/omi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/paperclip-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paperclip-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/paperclip-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ruflo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ruflo">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ruflo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/secrets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/secrets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/secrets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/twitter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/twitter">> = Specific
  const handler = {} as typeof import("../../../src/app/api/twitter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vault/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vault/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/workflows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflows">> = Specific
  const handler = {} as typeof import("../../../src/app/api/workflows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
